# https://github.com/helix-editor/helix/blob/master/runtime/themes/boo_berry.toml

inherits = "boo_berry"

"ui.background" = {}

"ui.cursor.primary.select" = { fg = "berry", bg = "bubblegum" }
"ui.cursor.primary.insert" = { fg = "berry", bg = "mint" }
